# Generated by Django 3.1 on 2021-08-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210812_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymeny',
            new_name='payment',
        ),
    ]
